name: 'Update Reference Screenshots'

on:
  workflow_dispatch:

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/build-core

  update-reference-screenshots:
    runs-on: ubuntu-latest
    needs: [build-core]
    steps:
      - uses: actions/checkout@v2
        # Normally, we could just push with the
        # default GITHUB_TOKEN, but that will
        # not cause the build workflow
        # to re-run. We use NKDuy's
        # Personal Access Token instead
        # to allow for this build workflow
        # to run when the screenshots are pushed.
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: ./.github/workflows/actions/update-reference-screenshots